<?xml version="1.0"?>

<robot 
  xmlns:xacro="http://www.ros.org/wiki/xacro" 
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" name="robot">

  <xacro:property name="body_length" value="0.20"/>
  <xacro:property name="body_width" value="0.13"/>
  <xacro:property name="body_height" value="0.05"/>
  <xacro:property name="front_wheel_radius" value="0.02"/>
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_width" value="0.027"/>
  <xacro:property name="lidar_height" value="0.08"/>
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </xacro:macro>
  <xacro:include filename="$(find myrobot)/urdf/robot.gazebo"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${body_height/2+0.025}"/>
      <material name="blue">
        <color rgba="0 0 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${body_height/2+0.025}"/>
    </collision>
    <xacro:default_inertial mass="0.6"/>
  </link>

  <link name="front_wheel">
    <visual>
      <geometry>
        <sphere radius="${front_wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${front_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <xacro:default_inertial mass="0.6"/>
  </link>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1</mu>
            <mu2>1</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1</mu>
            <mu2>1</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <link name="rplidar">
    <visual>
      <geometry>
        <cylinder length="${lidar_height}" radius="0.035"/>
      </geometry>
      <material name="green">
        <color rgba="0 0.5 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${lidar_height}" radius="0.035"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.1"/>
  </link>

  <joint name="base_to_front_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="front_wheel"/>
    <origin rpy="0 0 0" xyz="0.06 0 ${front_wheel_radius}"/>
    <axis xyz="1 1 1"/>
  </joint>
  <joint name="base_to_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin rpy="${-pi/2} 0 0" xyz="-0.07 ${body_width/2} ${wheel_radius}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="base_to_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin rpy="${-pi/2} 0 0" xyz="-0.07 ${-body_width/2} ${wheel_radius}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="base_to_rplidar" type="fixed">
    <parent link="base_link"/>
    <child link="rplidar"/>
    <origin rpy="0 0 0" xyz="0.02 0 ${lidar_height/2+body_height+0.025}"/>
    <axis xyz="0 0 1"/>
  </joint>

</robot>
